const themes = {
    laniricky: {
        title_color: 'ff9d00',
        icon_color: 'ff9d00',
        text_color: 'ffffff',
        bg_color: '5c3901',
        border_color: 'ff9d00',
    },
    blue_pink: {
        title_color: 'ff10f0',
        icon_color: '00f0ff',
        text_color: 'e0e0ff',
        bg_color: '0a0014',
        border_color: '2d1b69',
    },
    github_dark: {
        title_color: '58a6ff',
        icon_color: '1f6feb',
        text_color: 'c9d1d9',
        bg_color: '0d1117',
        border_color: '30363d',
    },
    github_light: {
        title_color: '24292f',
        icon_color: '0969da',
        text_color: '57606a',
        bg_color: 'ffffff',
        border_color: 'd0d7de',
    },
    moonlight: {
        title_color: 'c099ff',
        icon_color: '82aaff',
        text_color: 'b4c2f0',
        bg_color: '1e2030',
        border_color: '2f334d',
    },
    nord: {
        title_color: '88c0d0',
        icon_color: '5e81ac',
        text_color: 'd8dee9',
        bg_color: '2e3440',
        border_color: '3b4252',
    },
    dracula: {
        title_color: 'ff79c6',
        icon_color: 'bd93f9',
        text_color: 'f8f8f2',
        bg_color: '282a36',
        border_color: '44475a',
    },
    monokai: {
        title_color: 'f92672',
        icon_color: 'fd971f',
        text_color: 'f8f8f2',
        bg_color: '272822',
        border_color: '3e3d32',
    },
    ocean: {
        title_color: '4fc3f7',
        icon_color: '0288d1',
        text_color: 'b0bec5',
        bg_color: '0a1929',
        border_color: '1e3a5f',
    },
    synthwave: {
        title_color: 'ff6ec7',
        icon_color: 'ffd319',
        text_color: 'ffffff',
        bg_color: '2b213a',
        border_color: '495495',
    },
    midnight: {
        title_color: '64ffda',
        icon_color: '00e5ff',
        text_color: 'adbac7',
        bg_color: '0f1419',
        border_color: '2d333b',
    },
    slate: {
        title_color: 'f97316',
        icon_color: '3b82f6',
        text_color: '94a3b8',
        bg_color: '0f172a',
        border_color: '1e293b',
    },
    lavender_mint: {
        title_color: 'ffbb00',
        icon_color: '9c99b8',
        text_color: 'f5fff4',
        bg_color: '474150',
        border_color: '9c99b8',
    },
    ocean_sky: {
        title_color: '22819a',
        icon_color: '90c2e7',
        text_color: 'fef7f8',
        bg_color: 'cdd4dd',
        border_color: '22819a',
    },
    military_olive: {
        title_color: 'a7aa63',
        icon_color: 'eae6d2',
        text_color: 'eae6d2',
        bg_color: '121a1b',
        border_color: '505039',
    },
    neon_splash: {
        title_color: 'a935eb',
        icon_color: '87db20',
        text_color: 'ffffff',
        bg_color: '000000',
        border_color: 'a935eb',
    },
    autumn_spice: {
        title_color: 'fc5c02',
        icon_color: 'e2ceae',
        text_color: 'e2ceae',
        bg_color: '312b1e',
        border_color: '7c6b51',
    },
    cyber_teal: {
        title_color: '00ffd4',
        icon_color: '5465ff',
        text_color: 'd2ddff',
        bg_color: '050208',
        border_color: '5465ff',
    },
    purple_twilight: {
        title_color: 'a663cc',
        icon_color: '6f2dbd',
        text_color: 'fbfbfb',
        bg_color: '171123',
        border_color: '6f2dbd',
    },
    forest_sage: {
        title_color: 'acc8a2',
        icon_color: 'acc8a2',
        text_color: 'acc8a2',
        bg_color: '1a2517',
        border_color: 'acc8a2',
    },
    deep_ocean: {
        title_color: '2872a1',
        icon_color: 'cbdde9',
        text_color: 'cbdde9',
        bg_color: '2872a1',
        border_color: 'cbdde9',
    },
    sunset_steel: {
        title_color: 'fd802e',
        icon_color: 'fd802e',
        text_color: 'fd802e',
        bg_color: '233d4c',
        border_color: 'fd802e',
    },
    lavender_dream: {
        title_color: '5f4a8b',
        icon_color: 'fefacd',
        text_color: 'fefacd',
        bg_color: '5f4a8b',
        border_color: 'fefacd',
    },
    coral_sage: {
        title_color: '789a99',
        icon_color: 'ffd2c2',
        text_color: 'ffd2c2',
        bg_color: '789a99',
        border_color: 'ffd2c2',
    },
    crimson_gold: {
        title_color: 'f1e194',
        icon_color: 'f1e194',
        text_color: 'f1e194',
        bg_color: '5b0e14',
        border_color: 'f1e194',
    },
};

function getTheme(themeName = 'github_dark') {
    return themes[themeName] || themes.github_dark;
}

module.exports = { themes, getTheme };


